### ISSUE TITLE
El efecto sonoro para la victoria no está disponible.

### ISSUE THREAD

**Issue by cgosorio** [jlgarridol/BIE-Introduccion-Web#1]
En `effects` aparece `win.mp3`, pero no `victory.mp3` que es el efecto que tendría que reproducirse al finalizar el juego.

**Comment by cgosorio** [comment]
Se me acaba de ocurrir que aunque corrijas el problema en la versión final buena, podrías dejar ese error en la versión que entregas a los alumnos. Se les puede avisar de que hay un error y premio para el que lo descubra (siendo el premio el reconocimiento de sus pares, que tampoco tenemos nada para regalar).

**Comment by jlgarridol** [comment]
Lo voy a arreglar, pero me parece bien que descubran el error
